=head1 NAME

Plack::Middleware::CacheManager - Content cache manager

=head1 SYNOPSIS

  use Plack::Builder;
  use Cache::Memcached::Fast;

  builder {
      enable 'CacheManager' => +{
          cache  => Cache::Memcached::Fast->new(%memd_opt),
          keygen => sub {
              my $env = shift;
              return $env->{REQUEST_URI};
          },
          expire => 60,
          work   => ['set'],
      };
      $app;
  };

=head1 DESCRIPTION

Plack::Middleware::CacheManager is content cache manager.

=head1 AUTHOR

Kenta Sato E<lt>karupa@cpan.orgE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

